### ISSUE TITLE
*encoding in mrss_t can be NULL

### ISSUE THREAD

**Issue by iamleot** [flok99/rsstail#11]
*encoding in mrss_t can be NULL and this lead in crashing rsstail because it is
not NULL checked... In order to reproduce this issue please do:

```
$ rsstail -v -u http://netbsd.fi/atom.xml
Monitoring RSS feeds:
        http://netbsd.fi/atom.xml
Check interval: 900
Output current_encoding: UTF-8
Retrieving RSS feed 'http://netbsd.fi/atom.xml'...
Creating converter (null) -> UTF-8
Memory fault (core dumped)
```

The following patches fix this issue (and set as default encoding utf-8):

 https://gist.githubusercontent.com/iamleot/eb6dfaa8e6ffb9160b7e/raw/01f22484eafd6d3cda7545f8af0563fb0cf93434/patch-rsstail-nullencoding

**Comment by flok99** [comment]
Thanks!
Can you do a pull-request? Then I'll merge your change.

**Comment by iamleot** [comment]
Hello Folkert!

Folkert van Heusden writes:
> Thanks!
> Can you do a pull-request? Then I'll merge your change.
Done. Please let me know if I have missed something (it's the first
time that I do a pull-request... I'm sticked with mail with attached
patched behaviours :)).


Thank you very much for rsstail!
Ciao,
L.
