### ISSUE TITLE
Problem with multiple URLs and mrss_free()

### ISSUE THREAD

**Issue by iamleot** [flok99/rsstail#14]
Hello to the entire rsstail community,
I have investigated a bit regarding a problem that I have with rsstail
maybe is releated with issue #3.

It affects just if multiple URL are passed via the -u option.
In order to reproduce it:

> $ rsstail -i 2 -u 'http://www.vanheusden.com/rssfeed/' -u 'http://www.netbsd.org/changes/rss-netbsd.xml'
> Title: multitail 6.0
> Title: f-irc 1.23
> Title: f-irc v1.21
> Title: NetBSD 7.0_RC1 binaries available
> Title: New Security Advisories: NetBSD-SA2015-003 through 006 affecting NTPd, compatibility layers, libevent and OpenSSL
> Title: New Security Advisories: NetBSD-SA2015-001 Xorg server arbitrary code execution and -002 bind Denial of Service
> Memory fault (core dumped)

I have also tried to analyze the .core and the problem appears in
r2t.c:605 when mrss_free() is called (yep, there is also a typo in
r2t.c:609 (s/err_read/err_free/) but it isn't critical).

In particular the first mrss_free() is succesfull
(mrss_free(data_prev[0])) then when mrss_free(data_prev[1]) is performed
the problem occour. Unfortunately I tried to go a bit deeper in order to
fix the problem but the only workaround that I have found is to just
call mrss_free(data_prev) when all URLs are processed.

I'm using NetBSD/amd64 -current with the latest stable version of
libmrss (0.19.2). Both rsstail-2.0 and the master version of github
seems to have this problem.

Please let me know if you need further information!
Thank you in advance,
L.

**Comment by flok99** [comment]
Hi,

This problem is indeed a bug and is fixed in the current git-version.

thanks for reporting

On Tue, Aug 18, 2015 at 5:00 PM, Leonardo Taccari <notifications@github.com>
wrote:

> Hello to the entire rsstail community,
> I have investigated a bit regarding a problem that I have with rsstail
> maybe is releated with issue #3
> <https://github.com/flok99/rsstail/issues/3>.
>
> It affects just if multiple URL are passed via the -u option.
> In order to reproduce it:
>
> $ rsstail -i 2 -u 'http://www.vanheusden.com/rssfeed/' -u '
> http://www.netbsd.org/changes/rss-netbsd.xml'
> Title: multitail 6.0
> Title: f-irc 1.23
> Title: f-irc v1.21
> Title: NetBSD 7.0_RC1 binaries available
> Title: New Security Advisories: NetBSD-SA2015-003 through 006 affecting
> NTPd, compatibility layers, libevent and OpenSSL
> Title: New Security Advisories: NetBSD-SA2015-001 Xorg server arbitrary
> code execution and -002 bind Denial of Service
> Memory fault (core dumped)
>
> I have also tried to analyze the .core and the problem appears in
> r2t.c:605 when mrss_free() is called (yep, there is also a typo in
> r2t.c:609 (s/err_read/err_free/) but it isn't critical).
>
> In particular the first mrss_free() is succesfull
> (mrss_free(data_prev[0])) then when mrss_free(data_prev[1]) is performed
> the problem occour. Unfortunately I tried to go a bit deeper in order to
> fix the problem but the only workaround that I have found is to just
> call mrss_free(data_prev) when all URLs are processed.
>
> I'm using NetBSD/amd64 -current with the latest stable version of
> libmrss (0.19.2). Both rsstail-2.0 and the master version of github
> seems to have this problem.
>
> Please let me know if you need further information!
> Thank you in advance,
> L.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flok99/rsstail/issues/14>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info

**Comment by iamleot** [comment]
Hello Folkert,

Folkert van Heusden writes:
> [...]
> This problem is indeed a bug and is fixed in the current git-version.
> 
> thanks for reporting
> [...]
Thank you very much for the quick fix!


Ciao,
L.
