### ISSUE TITLE
Published Day is always Sun(day)

### ISSUE THREAD

**Issue by tvjon** [flok99/rsstail#28]
Any feed using -p reports correct date & time but not the day.

**Comment by Necior** [comment]
After a short glimpse at the code, it seems like a problem lies in `libmrss`.

In version 0.19.2 of `libmrss`, when parsing date, it doesn't set `tm_wday` (day of week) in a time structure. Above it fills the whole structures with zeros, hence the Sunday.

*Note*: I only peeked at the code for a few minutes. I might be wrong.

**Comment by tvjon** [comment]
Necior, thank you. Bakulf is going to take a look.

**Comment by tvjon** [comment]
Ok, Bakulf has fixed the issue, thank you.
