### ISSUE TITLE
Reversing order on empty RSS feed leads to segmentation fault

### ISSUE THREAD

**Issue by Necior** [flok99/rsstail#6]
It seems like reversing order on empty RSS feed leads to segmentation fault.

To reproduce run `rsstail -r -u http://testiiing.tumblr.com/rss ` (or with any other empty feed).

It affects `rsstail v1.8` (from Debian Sid) and newest code from master (e048993303b2b04c3564ff04498be8d88c254d3f).

This issue might be related with #3.

**Comment by Necior** [comment]
Should we bump version number (e.g. to 1.9.1)?

**Comment by flok99** [comment]
yes, sounds good

On Thu, Apr 30, 2015 at 12:14 PM, Adrian Sadłocha <notifications@github.com>
wrote:

> Should we bump version number (e.g. to 1.9.1)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flok99/rsstail/issues/6#issuecomment-97728644>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info

**Comment by wturrell** [comment]
re: #3, I'm also experiencing that issue on OSX (it's fine on Debian) for `v1.8` – but I can confirm I get segfaults  regardless of whether the feed is "normal" or reversed.
